from __future__ import annotations

NAVER_HOME_MAX_LENGTH = 40
NAVER_HOME_VARIATIONS = 2
BLOG_VARIATIONS = 2
YEAR_TEXT = "2026 최신"
TITLE_QUALITY_PASS_SCORE = 84
TITLE_QUALITY_REVIEW_SCORE = 75
NAVER_HOME_AI_REWRITE_SCORE_THRESHOLD = 68
